name: "Guice-Shop"

on: 
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASS }}
          SERVER_ID: setup-jfrog-cli-server
          
      - name: Configure RT Repos        
        run: |
          jf npm-config --server-id-resolve=setup-jfrog-cli-server --server-id-deploy=setup-jfrog-cli-server --repo-resolve=${{ vars.NPM_VIRTUAL_REPO }} --repo-deploy=${{ vars.NPM_VIRTUAL_REPO }}
      
      - name: Test JFrog CLI
        run: |
          jf c show
          jf rt ping
          jf -v
      
      - name: Install npm Project
        run: jf npm install
      
      - name: Login to Docker Enviroment
        run: docker login ${{ vars.DOCKER_REG_SRV }} -u ${{ secrets.JF_USER }} -p ${{ secrets.JF_PASS }} 
      - name: Build and Tag Docker Image
        run: |
          docker build -t ohad-juiceshop-gha .
          docker tag ohad-juiceshop-gha:latest ohadz.jfrog.io/docker/ohad-juiceshop-gha:latest

      - name: Push Docker Image to RT
        run: jf docker push ohadz.jfrog.io/docker/ohad-juiceshop-gha:latest
      
      - name: Collect and Publish Build Info
        run: |
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
          
      - name: Scan Build
        run: jf bs --fail=false
          
    